start cmd /c "go run ./cmd/media/main.go"
start cmd /c "go run ./cmd/user/main.go"
start cmd /c "go run ./cmd/components/logger/main.go"
start cmd /c "go run ./cmd/video/main.go"
start cmd /c "go run ./cmd/interaction/main.go"
start cmd /c "go run ./cmd/gateway/main.go"
start cmd /c "go run ./cmd/components/scheduler/main.go"
start cmd /c "go run ./cmd/components/event_consumer/main.go"