// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------- 公开视频视图（给 Feed / 访客 / 推荐） ----------
type PublicVideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicVideoInfo) Reset() {
	*x = PublicVideoInfo{}
	mi := &file_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicVideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicVideoInfo) ProtoMessage() {}

func (x *PublicVideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicVideoInfo.ProtoReflect.Descriptor instead.
func (*PublicVideoInfo) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

func (x *PublicVideoInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicVideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublicVideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *PublicVideoInfo) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *PublicVideoInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PublicVideoInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ---------- 作者视图（我的视频 / 管理后台） ----------
type AuthorVideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                     // 0-待审核 1-通过 2-拒绝
	IsPublic      int32                  `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"` // 0-私密 1-公开
	Duration      int64                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorVideoInfo) Reset() {
	*x = AuthorVideoInfo{}
	mi := &file_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorVideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorVideoInfo) ProtoMessage() {}

func (x *AuthorVideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorVideoInfo.ProtoReflect.Descriptor instead.
func (*AuthorVideoInfo) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorVideoInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthorVideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AuthorVideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthorVideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *AuthorVideoInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuthorVideoInfo) GetIsPublic() int32 {
	if x != nil {
		return x.IsPublic
	}
	return 0
}

func (x *AuthorVideoInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AuthorVideoInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuthorVideoInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ---------- 内部完整模型（仅服务内部 / 管理端使用） ----------
type InternalVideoInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId        string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	SourceObjectKey string                 `protobuf:"bytes,5,opt,name=source_object_key,json=sourceObjectKey,proto3" json:"source_object_key,omitempty"` // MinIO / OSS 内部引用
	CoverUrl        string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Status          int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	IsPublic        int32                  `protobuf:"varint,8,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Duration        int64                  `protobuf:"varint,9,opt,name=duration,proto3" json:"duration,omitempty"`
	VideoMeta       string                 `protobuf:"bytes,10,opt,name=video_meta,json=videoMeta,proto3" json:"video_meta,omitempty"` // JSON：分辨率 / 编码 / 码率等
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InternalVideoInfo) Reset() {
	*x = InternalVideoInfo{}
	mi := &file_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalVideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalVideoInfo) ProtoMessage() {}

func (x *InternalVideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalVideoInfo.ProtoReflect.Descriptor instead.
func (*InternalVideoInfo) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{2}
}

func (x *InternalVideoInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InternalVideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InternalVideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InternalVideoInfo) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *InternalVideoInfo) GetSourceObjectKey() string {
	if x != nil {
		return x.SourceObjectKey
	}
	return ""
}

func (x *InternalVideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *InternalVideoInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InternalVideoInfo) GetIsPublic() int32 {
	if x != nil {
		return x.IsPublic
	}
	return 0
}

func (x *InternalVideoInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *InternalVideoInfo) GetVideoMeta() string {
	if x != nil {
		return x.VideoMeta
	}
	return ""
}

func (x *InternalVideoInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InternalVideoInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetVideoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*GetVideoResponse_PublicVideo
	//	*GetVideoResponse_AuthorVideo
	Data          isGetVideoResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoResponse) Reset() {
	*x = GetVideoResponse{}
	mi := &file_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoResponse) ProtoMessage() {}

func (x *GetVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoResponse.ProtoReflect.Descriptor instead.
func (*GetVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideoResponse) GetData() isGetVideoResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetVideoResponse) GetPublicVideo() *PublicVideoInfo {
	if x != nil {
		if x, ok := x.Data.(*GetVideoResponse_PublicVideo); ok {
			return x.PublicVideo
		}
	}
	return nil
}

func (x *GetVideoResponse) GetAuthorVideo() *AuthorVideoInfo {
	if x != nil {
		if x, ok := x.Data.(*GetVideoResponse_AuthorVideo); ok {
			return x.AuthorVideo
		}
	}
	return nil
}

type isGetVideoResponse_Data interface {
	isGetVideoResponse_Data()
}

type GetVideoResponse_PublicVideo struct {
	PublicVideo *PublicVideoInfo `protobuf:"bytes,1,opt,name=public_video,json=publicVideo,proto3,oneof"`
}

type GetVideoResponse_AuthorVideo struct {
	AuthorVideo *AuthorVideoInfo `protobuf:"bytes,2,opt,name=author_video,json=authorVideo,proto3,oneof"`
}

func (*GetVideoResponse_PublicVideo) isGetVideoResponse_Data() {}

func (*GetVideoResponse_AuthorVideo) isGetVideoResponse_Data() {}

// 创建视频
type CreateVideoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SourceObjectKey string                 `protobuf:"bytes,3,opt,name=source_object_key,json=sourceObjectKey,proto3" json:"source_object_key,omitempty"`
	CoverUrl        string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVideoRequest) GetSourceObjectKey() string {
	if x != nil {
		return x.SourceObjectKey
	}
	return ""
}

func (x *CreateVideoRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

// 获取视频
type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

// 更新视频
type UpdateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	IsPublic      int32                  `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoRequest) Reset() {
	*x = UpdateVideoRequest{}
	mi := &file_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoRequest) ProtoMessage() {}

func (x *UpdateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateVideoRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *UpdateVideoRequest) GetIsPublic() int32 {
	if x != nil {
		return x.IsPublic
	}
	return 0
}

// 删除视频
type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type DeleteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResponse) Reset() {
	*x = DeleteVideoResponse{}
	mi := &file_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResponse) ProtoMessage() {}

func (x *DeleteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 查看某个用户的公开视频（访客）
type ListUserPublishedVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPublishedVideosRequest) Reset() {
	*x = ListUserPublishedVideosRequest{}
	mi := &file_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPublishedVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPublishedVideosRequest) ProtoMessage() {}

func (x *ListUserPublishedVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPublishedVideosRequest.ProtoReflect.Descriptor instead.
func (*ListUserPublishedVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserPublishedVideosRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserPublishedVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserPublishedVideosRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListUserPublishedVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*PublicVideoInfo     `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPublishedVideosResponse) Reset() {
	*x = ListUserPublishedVideosResponse{}
	mi := &file_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPublishedVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPublishedVideosResponse) ProtoMessage() {}

func (x *ListUserPublishedVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPublishedVideosResponse.ProtoReflect.Descriptor instead.
func (*ListUserPublishedVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserPublishedVideosResponse) GetVideos() []*PublicVideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListUserPublishedVideosResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 查看我自己的视频（作者）
type ListMyVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyVideosRequest) Reset() {
	*x = ListMyVideosRequest{}
	mi := &file_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyVideosRequest) ProtoMessage() {}

func (x *ListMyVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyVideosRequest.ProtoReflect.Descriptor instead.
func (*ListMyVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{11}
}

func (x *ListMyVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyVideosRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMyVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*AuthorVideoInfo     `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyVideosResponse) Reset() {
	*x = ListMyVideosResponse{}
	mi := &file_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyVideosResponse) ProtoMessage() {}

func (x *ListMyVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyVideosResponse.ProtoReflect.Descriptor instead.
func (*ListMyVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{12}
}

func (x *ListMyVideosResponse) GetVideos() []*AuthorVideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListMyVideosResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_video_proto protoreflect.FileDescriptor

const file_video_proto_rawDesc = "" +
	"\n" +
	"\vvideo.proto\x12\x10stream_hub.video\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x01\n" +
	"\x0fPublicVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbd\x02\n" +
	"\x0fAuthorVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\x05R\bisPublic\x12\x1a\n" +
	"\bduration\x18\a \x01(\x03R\bduration\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa7\x03\n" +
	"\x11InternalVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12*\n" +
	"\x11source_object_key\x18\x05 \x01(\tR\x0fsourceObjectKey\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1b\n" +
	"\tis_public\x18\b \x01(\x05R\bisPublic\x12\x1a\n" +
	"\bduration\x18\t \x01(\x03R\bduration\x12\x1d\n" +
	"\n" +
	"video_meta\x18\n" +
	" \x01(\tR\tvideoMeta\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaa\x01\n" +
	"\x10GetVideoResponse\x12F\n" +
	"\fpublic_video\x18\x01 \x01(\v2!.stream_hub.video.PublicVideoInfoH\x00R\vpublicVideo\x12F\n" +
	"\fauthor_video\x18\x02 \x01(\v2!.stream_hub.video.AuthorVideoInfoH\x00R\vauthorVideoB\x06\n" +
	"\x04data\"\x95\x01\n" +
	"\x12CreateVideoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11source_object_key\x18\x03 \x01(\tR\x0fsourceObjectKey\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\",\n" +
	"\x0fGetVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"\xa1\x01\n" +
	"\x12UpdateVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\x05R\bisPublic\"/\n" +
	"\x12DeleteVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"I\n" +
	"\x13DeleteVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"a\n" +
	"\x1eListUserPublishedVideosRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"r\n" +
	"\x1fListUserPublishedVideosResponse\x129\n" +
	"\x06videos\x18\x01 \x03(\v2!.stream_hub.video.PublicVideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"=\n" +
	"\x13ListMyVideosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"g\n" +
	"\x14ListMyVideosResponse\x129\n" +
	"\x06videos\x18\x01 \x03(\v2!.stream_hub.video.AuthorVideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xcc\x04\n" +
	"\fVideoService\x12V\n" +
	"\vCreateVideo\x12$.stream_hub.video.CreateVideoRequest\x1a!.stream_hub.video.AuthorVideoInfo\x12Q\n" +
	"\bGetVideo\x12!.stream_hub.video.GetVideoRequest\x1a\".stream_hub.video.GetVideoResponse\x12V\n" +
	"\vUpdateVideo\x12$.stream_hub.video.UpdateVideoRequest\x1a!.stream_hub.video.AuthorVideoInfo\x12Z\n" +
	"\vDeleteVideo\x12$.stream_hub.video.DeleteVideoRequest\x1a%.stream_hub.video.DeleteVideoResponse\x12~\n" +
	"\x17ListUserPublishedVideos\x120.stream_hub.video.ListUserPublishedVideosRequest\x1a1.stream_hub.video.ListUserPublishedVideosResponse\x12]\n" +
	"\fListMyVideos\x12%.stream_hub.video.ListMyVideosRequest\x1a&.stream_hub.video.ListMyVideosResponseB\tZ\a./videob\x06proto3"

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData []byte
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)))
	})
	return file_video_proto_rawDescData
}

var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_video_proto_goTypes = []any{
	(*PublicVideoInfo)(nil),                 // 0: stream_hub.video.PublicVideoInfo
	(*AuthorVideoInfo)(nil),                 // 1: stream_hub.video.AuthorVideoInfo
	(*InternalVideoInfo)(nil),               // 2: stream_hub.video.InternalVideoInfo
	(*GetVideoResponse)(nil),                // 3: stream_hub.video.GetVideoResponse
	(*CreateVideoRequest)(nil),              // 4: stream_hub.video.CreateVideoRequest
	(*GetVideoRequest)(nil),                 // 5: stream_hub.video.GetVideoRequest
	(*UpdateVideoRequest)(nil),              // 6: stream_hub.video.UpdateVideoRequest
	(*DeleteVideoRequest)(nil),              // 7: stream_hub.video.DeleteVideoRequest
	(*DeleteVideoResponse)(nil),             // 8: stream_hub.video.DeleteVideoResponse
	(*ListUserPublishedVideosRequest)(nil),  // 9: stream_hub.video.ListUserPublishedVideosRequest
	(*ListUserPublishedVideosResponse)(nil), // 10: stream_hub.video.ListUserPublishedVideosResponse
	(*ListMyVideosRequest)(nil),             // 11: stream_hub.video.ListMyVideosRequest
	(*ListMyVideosResponse)(nil),            // 12: stream_hub.video.ListMyVideosResponse
	(*timestamppb.Timestamp)(nil),           // 13: google.protobuf.Timestamp
}
var file_video_proto_depIdxs = []int32{
	13, // 0: stream_hub.video.PublicVideoInfo.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: stream_hub.video.AuthorVideoInfo.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: stream_hub.video.AuthorVideoInfo.updated_at:type_name -> google.protobuf.Timestamp
	13, // 3: stream_hub.video.InternalVideoInfo.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: stream_hub.video.InternalVideoInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: stream_hub.video.GetVideoResponse.public_video:type_name -> stream_hub.video.PublicVideoInfo
	1,  // 6: stream_hub.video.GetVideoResponse.author_video:type_name -> stream_hub.video.AuthorVideoInfo
	0,  // 7: stream_hub.video.ListUserPublishedVideosResponse.videos:type_name -> stream_hub.video.PublicVideoInfo
	1,  // 8: stream_hub.video.ListMyVideosResponse.videos:type_name -> stream_hub.video.AuthorVideoInfo
	4,  // 9: stream_hub.video.VideoService.CreateVideo:input_type -> stream_hub.video.CreateVideoRequest
	5,  // 10: stream_hub.video.VideoService.GetVideo:input_type -> stream_hub.video.GetVideoRequest
	6,  // 11: stream_hub.video.VideoService.UpdateVideo:input_type -> stream_hub.video.UpdateVideoRequest
	7,  // 12: stream_hub.video.VideoService.DeleteVideo:input_type -> stream_hub.video.DeleteVideoRequest
	9,  // 13: stream_hub.video.VideoService.ListUserPublishedVideos:input_type -> stream_hub.video.ListUserPublishedVideosRequest
	11, // 14: stream_hub.video.VideoService.ListMyVideos:input_type -> stream_hub.video.ListMyVideosRequest
	1,  // 15: stream_hub.video.VideoService.CreateVideo:output_type -> stream_hub.video.AuthorVideoInfo
	3,  // 16: stream_hub.video.VideoService.GetVideo:output_type -> stream_hub.video.GetVideoResponse
	1,  // 17: stream_hub.video.VideoService.UpdateVideo:output_type -> stream_hub.video.AuthorVideoInfo
	8,  // 18: stream_hub.video.VideoService.DeleteVideo:output_type -> stream_hub.video.DeleteVideoResponse
	10, // 19: stream_hub.video.VideoService.ListUserPublishedVideos:output_type -> stream_hub.video.ListUserPublishedVideosResponse
	12, // 20: stream_hub.video.VideoService.ListMyVideos:output_type -> stream_hub.video.ListMyVideosResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	file_video_proto_msgTypes[3].OneofWrappers = []any{
		(*GetVideoResponse_PublicVideo)(nil),
		(*GetVideoResponse_AuthorVideo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
