// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: video.proto

package video

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for VideoService service

func NewVideoServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for VideoService service

type VideoService interface {
	// 创建视频（作者）
	CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...client.CallOption) (*AuthorVideoInfo, error)
	// 获取视频详情
	// - 作者：返回 AuthorVideoInfo
	// - 非作者：返回 PublicVideoInfo
	GetVideo(ctx context.Context, in *GetVideoRequest, opts ...client.CallOption) (*GetVideoResponse, error)
	// 更新视频元数据（仅作者）
	UpdateVideo(ctx context.Context, in *UpdateVideoRequest, opts ...client.CallOption) (*AuthorVideoInfo, error)
	// 删除视频（仅作者）
	DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...client.CallOption) (*DeleteVideoResponse, error)
	// 获取某用户的公开视频列表（访客视角）
	ListUserPublishedVideos(ctx context.Context, in *ListUserPublishedVideosRequest, opts ...client.CallOption) (*ListUserPublishedVideosResponse, error)
	// 获取我自己的视频列表（作者视角）
	ListMyVideos(ctx context.Context, in *ListMyVideosRequest, opts ...client.CallOption) (*ListMyVideosResponse, error)
}

type videoService struct {
	c    client.Client
	name string
}

func NewVideoService(name string, c client.Client) VideoService {
	return &videoService{
		c:    c,
		name: name,
	}
}

func (c *videoService) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...client.CallOption) (*AuthorVideoInfo, error) {
	req := c.c.NewRequest(c.name, "VideoService.CreateVideo", in)
	out := new(AuthorVideoInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...client.CallOption) (*GetVideoResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.GetVideo", in)
	out := new(GetVideoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) UpdateVideo(ctx context.Context, in *UpdateVideoRequest, opts ...client.CallOption) (*AuthorVideoInfo, error) {
	req := c.c.NewRequest(c.name, "VideoService.UpdateVideo", in)
	out := new(AuthorVideoInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...client.CallOption) (*DeleteVideoResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.DeleteVideo", in)
	out := new(DeleteVideoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) ListUserPublishedVideos(ctx context.Context, in *ListUserPublishedVideosRequest, opts ...client.CallOption) (*ListUserPublishedVideosResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.ListUserPublishedVideos", in)
	out := new(ListUserPublishedVideosResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) ListMyVideos(ctx context.Context, in *ListMyVideosRequest, opts ...client.CallOption) (*ListMyVideosResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.ListMyVideos", in)
	out := new(ListMyVideosResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VideoService service

type VideoServiceHandler interface {
	// 创建视频（作者）
	CreateVideo(context.Context, *CreateVideoRequest, *AuthorVideoInfo) error
	// 获取视频详情
	// - 作者：返回 AuthorVideoInfo
	// - 非作者：返回 PublicVideoInfo
	GetVideo(context.Context, *GetVideoRequest, *GetVideoResponse) error
	// 更新视频元数据（仅作者）
	UpdateVideo(context.Context, *UpdateVideoRequest, *AuthorVideoInfo) error
	// 删除视频（仅作者）
	DeleteVideo(context.Context, *DeleteVideoRequest, *DeleteVideoResponse) error
	// 获取某用户的公开视频列表（访客视角）
	ListUserPublishedVideos(context.Context, *ListUserPublishedVideosRequest, *ListUserPublishedVideosResponse) error
	// 获取我自己的视频列表（作者视角）
	ListMyVideos(context.Context, *ListMyVideosRequest, *ListMyVideosResponse) error
}

func RegisterVideoServiceHandler(s server.Server, hdlr VideoServiceHandler, opts ...server.HandlerOption) error {
	type videoService interface {
		CreateVideo(ctx context.Context, in *CreateVideoRequest, out *AuthorVideoInfo) error
		GetVideo(ctx context.Context, in *GetVideoRequest, out *GetVideoResponse) error
		UpdateVideo(ctx context.Context, in *UpdateVideoRequest, out *AuthorVideoInfo) error
		DeleteVideo(ctx context.Context, in *DeleteVideoRequest, out *DeleteVideoResponse) error
		ListUserPublishedVideos(ctx context.Context, in *ListUserPublishedVideosRequest, out *ListUserPublishedVideosResponse) error
		ListMyVideos(ctx context.Context, in *ListMyVideosRequest, out *ListMyVideosResponse) error
	}
	type VideoService struct {
		videoService
	}
	h := &videoServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&VideoService{h}, opts...))
}

type videoServiceHandler struct {
	VideoServiceHandler
}

func (h *videoServiceHandler) CreateVideo(ctx context.Context, in *CreateVideoRequest, out *AuthorVideoInfo) error {
	return h.VideoServiceHandler.CreateVideo(ctx, in, out)
}

func (h *videoServiceHandler) GetVideo(ctx context.Context, in *GetVideoRequest, out *GetVideoResponse) error {
	return h.VideoServiceHandler.GetVideo(ctx, in, out)
}

func (h *videoServiceHandler) UpdateVideo(ctx context.Context, in *UpdateVideoRequest, out *AuthorVideoInfo) error {
	return h.VideoServiceHandler.UpdateVideo(ctx, in, out)
}

func (h *videoServiceHandler) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, out *DeleteVideoResponse) error {
	return h.VideoServiceHandler.DeleteVideo(ctx, in, out)
}

func (h *videoServiceHandler) ListUserPublishedVideos(ctx context.Context, in *ListUserPublishedVideosRequest, out *ListUserPublishedVideosResponse) error {
	return h.VideoServiceHandler.ListUserPublishedVideos(ctx, in, out)
}

func (h *videoServiceHandler) ListMyVideos(ctx context.Context, in *ListMyVideosRequest, out *ListMyVideosResponse) error {
	return h.VideoServiceHandler.ListMyVideos(ctx, in, out)
}
