// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: video.proto

package video

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for VideoService service

func NewVideoServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for VideoService service

type VideoService interface {
	CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...client.CallOption) (*AuthorVideoInfo, error)
	GetVideo(ctx context.Context, in *GetVideoRequest, opts ...client.CallOption) (*GetVideoResponse, error)
	UpdateVideo(ctx context.Context, in *UpdateVideoRequest, opts ...client.CallOption) (*AuthorVideoInfo, error)
	DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...client.CallOption) (*DeleteVideoResponse, error)
	ListUserPublishedVideos(ctx context.Context, in *ListUserPublishedVideosRequest, opts ...client.CallOption) (*ListUserPublishedVideosResponse, error)
	ListMyVideos(ctx context.Context, in *ListMyVideosRequest, opts ...client.CallOption) (*ListMyVideosResponse, error)
	ListFeedVideos(ctx context.Context, in *ListFeedVideosRequest, opts ...client.CallOption) (*ListFeedVideosResponse, error)
	SearchVideos(ctx context.Context, in *SearchVideosRequest, opts ...client.CallOption) (*SearchVideosResponse, error)
	ListHotVideos(ctx context.Context, in *ListHotVideosRequest, opts ...client.CallOption) (*ListHotVideosResponse, error)
}

type videoService struct {
	c    client.Client
	name string
}

func NewVideoService(name string, c client.Client) VideoService {
	return &videoService{
		c:    c,
		name: name,
	}
}

func (c *videoService) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...client.CallOption) (*AuthorVideoInfo, error) {
	req := c.c.NewRequest(c.name, "VideoService.CreateVideo", in)
	out := new(AuthorVideoInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...client.CallOption) (*GetVideoResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.GetVideo", in)
	out := new(GetVideoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) UpdateVideo(ctx context.Context, in *UpdateVideoRequest, opts ...client.CallOption) (*AuthorVideoInfo, error) {
	req := c.c.NewRequest(c.name, "VideoService.UpdateVideo", in)
	out := new(AuthorVideoInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...client.CallOption) (*DeleteVideoResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.DeleteVideo", in)
	out := new(DeleteVideoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) ListUserPublishedVideos(ctx context.Context, in *ListUserPublishedVideosRequest, opts ...client.CallOption) (*ListUserPublishedVideosResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.ListUserPublishedVideos", in)
	out := new(ListUserPublishedVideosResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) ListMyVideos(ctx context.Context, in *ListMyVideosRequest, opts ...client.CallOption) (*ListMyVideosResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.ListMyVideos", in)
	out := new(ListMyVideosResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) ListFeedVideos(ctx context.Context, in *ListFeedVideosRequest, opts ...client.CallOption) (*ListFeedVideosResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.ListFeedVideos", in)
	out := new(ListFeedVideosResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) SearchVideos(ctx context.Context, in *SearchVideosRequest, opts ...client.CallOption) (*SearchVideosResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.SearchVideos", in)
	out := new(SearchVideosResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoService) ListHotVideos(ctx context.Context, in *ListHotVideosRequest, opts ...client.CallOption) (*ListHotVideosResponse, error) {
	req := c.c.NewRequest(c.name, "VideoService.ListHotVideos", in)
	out := new(ListHotVideosResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VideoService service

type VideoServiceHandler interface {
	CreateVideo(context.Context, *CreateVideoRequest, *AuthorVideoInfo) error
	GetVideo(context.Context, *GetVideoRequest, *GetVideoResponse) error
	UpdateVideo(context.Context, *UpdateVideoRequest, *AuthorVideoInfo) error
	DeleteVideo(context.Context, *DeleteVideoRequest, *DeleteVideoResponse) error
	ListUserPublishedVideos(context.Context, *ListUserPublishedVideosRequest, *ListUserPublishedVideosResponse) error
	ListMyVideos(context.Context, *ListMyVideosRequest, *ListMyVideosResponse) error
	ListFeedVideos(context.Context, *ListFeedVideosRequest, *ListFeedVideosResponse) error
	SearchVideos(context.Context, *SearchVideosRequest, *SearchVideosResponse) error
	ListHotVideos(context.Context, *ListHotVideosRequest, *ListHotVideosResponse) error
}

func RegisterVideoServiceHandler(s server.Server, hdlr VideoServiceHandler, opts ...server.HandlerOption) error {
	type videoService interface {
		CreateVideo(ctx context.Context, in *CreateVideoRequest, out *AuthorVideoInfo) error
		GetVideo(ctx context.Context, in *GetVideoRequest, out *GetVideoResponse) error
		UpdateVideo(ctx context.Context, in *UpdateVideoRequest, out *AuthorVideoInfo) error
		DeleteVideo(ctx context.Context, in *DeleteVideoRequest, out *DeleteVideoResponse) error
		ListUserPublishedVideos(ctx context.Context, in *ListUserPublishedVideosRequest, out *ListUserPublishedVideosResponse) error
		ListMyVideos(ctx context.Context, in *ListMyVideosRequest, out *ListMyVideosResponse) error
		ListFeedVideos(ctx context.Context, in *ListFeedVideosRequest, out *ListFeedVideosResponse) error
		SearchVideos(ctx context.Context, in *SearchVideosRequest, out *SearchVideosResponse) error
		ListHotVideos(ctx context.Context, in *ListHotVideosRequest, out *ListHotVideosResponse) error
	}
	type VideoService struct {
		videoService
	}
	h := &videoServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&VideoService{h}, opts...))
}

type videoServiceHandler struct {
	VideoServiceHandler
}

func (h *videoServiceHandler) CreateVideo(ctx context.Context, in *CreateVideoRequest, out *AuthorVideoInfo) error {
	return h.VideoServiceHandler.CreateVideo(ctx, in, out)
}

func (h *videoServiceHandler) GetVideo(ctx context.Context, in *GetVideoRequest, out *GetVideoResponse) error {
	return h.VideoServiceHandler.GetVideo(ctx, in, out)
}

func (h *videoServiceHandler) UpdateVideo(ctx context.Context, in *UpdateVideoRequest, out *AuthorVideoInfo) error {
	return h.VideoServiceHandler.UpdateVideo(ctx, in, out)
}

func (h *videoServiceHandler) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, out *DeleteVideoResponse) error {
	return h.VideoServiceHandler.DeleteVideo(ctx, in, out)
}

func (h *videoServiceHandler) ListUserPublishedVideos(ctx context.Context, in *ListUserPublishedVideosRequest, out *ListUserPublishedVideosResponse) error {
	return h.VideoServiceHandler.ListUserPublishedVideos(ctx, in, out)
}

func (h *videoServiceHandler) ListMyVideos(ctx context.Context, in *ListMyVideosRequest, out *ListMyVideosResponse) error {
	return h.VideoServiceHandler.ListMyVideos(ctx, in, out)
}

func (h *videoServiceHandler) ListFeedVideos(ctx context.Context, in *ListFeedVideosRequest, out *ListFeedVideosResponse) error {
	return h.VideoServiceHandler.ListFeedVideos(ctx, in, out)
}

func (h *videoServiceHandler) SearchVideos(ctx context.Context, in *SearchVideosRequest, out *SearchVideosResponse) error {
	return h.VideoServiceHandler.SearchVideos(ctx, in, out)
}

func (h *videoServiceHandler) ListHotVideos(ctx context.Context, in *ListHotVideosRequest, out *ListHotVideosResponse) error {
	return h.VideoServiceHandler.ListHotVideos(ctx, in, out)
}
