// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: interaction.proto

package interaction

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for InteractionService service

func NewInteractionServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for InteractionService service

type InteractionService interface {
	// 点赞
	CreateLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*ActionResponse, error)
	DeleteLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*ActionResponse, error)
	IsLike(ctx context.Context, in *IsLikeRequest, opts ...client.CallOption) (*IsLikeResponse, error)
	ListLikes(ctx context.Context, in *ListLikesRequest, opts ...client.CallOption) (*ListLikesResponse, error)
	// 收藏
	CreateFavorite(ctx context.Context, in *FavoriteRequest, opts ...client.CallOption) (*ActionResponse, error)
	DeleteFavorite(ctx context.Context, in *FavoriteRequest, opts ...client.CallOption) (*ActionResponse, error)
	IsFavorite(ctx context.Context, in *IsFavoriteRequest, opts ...client.CallOption) (*IsFavoriteResponse, error)
	// 关注
	CreateFollow(ctx context.Context, in *FollowRequest, opts ...client.CallOption) (*ActionResponse, error)
	DeleteFollow(ctx context.Context, in *FollowRequest, opts ...client.CallOption) (*ActionResponse, error)
	IsFollow(ctx context.Context, in *IsFollowRequest, opts ...client.CallOption) (*IsFollowResponse, error)
	ListFollowers(ctx context.Context, in *ListFollowersRequest, opts ...client.CallOption) (*ListFollowersResponse, error)
	ListFollowings(ctx context.Context, in *ListFollowingsRequest, opts ...client.CallOption) (*ListFollowingsResponse, error)
	// 评论
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...client.CallOption) (*Comment, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...client.CallOption) (*ActionResponse, error)
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...client.CallOption) (*ListCommentsResponse, error)
}

type interactionService struct {
	c    client.Client
	name string
}

func NewInteractionService(name string, c client.Client) InteractionService {
	return &interactionService{
		c:    c,
		name: name,
	}
}

func (c *interactionService) CreateLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.CreateLike", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) DeleteLike(ctx context.Context, in *LikeRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.DeleteLike", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) IsLike(ctx context.Context, in *IsLikeRequest, opts ...client.CallOption) (*IsLikeResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.IsLike", in)
	out := new(IsLikeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) ListLikes(ctx context.Context, in *ListLikesRequest, opts ...client.CallOption) (*ListLikesResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.ListLikes", in)
	out := new(ListLikesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) CreateFavorite(ctx context.Context, in *FavoriteRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.CreateFavorite", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) DeleteFavorite(ctx context.Context, in *FavoriteRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.DeleteFavorite", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) IsFavorite(ctx context.Context, in *IsFavoriteRequest, opts ...client.CallOption) (*IsFavoriteResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.IsFavorite", in)
	out := new(IsFavoriteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) CreateFollow(ctx context.Context, in *FollowRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.CreateFollow", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) DeleteFollow(ctx context.Context, in *FollowRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.DeleteFollow", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) IsFollow(ctx context.Context, in *IsFollowRequest, opts ...client.CallOption) (*IsFollowResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.IsFollow", in)
	out := new(IsFollowResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) ListFollowers(ctx context.Context, in *ListFollowersRequest, opts ...client.CallOption) (*ListFollowersResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.ListFollowers", in)
	out := new(ListFollowersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) ListFollowings(ctx context.Context, in *ListFollowingsRequest, opts ...client.CallOption) (*ListFollowingsResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.ListFollowings", in)
	out := new(ListFollowingsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...client.CallOption) (*Comment, error) {
	req := c.c.NewRequest(c.name, "InteractionService.CreateComment", in)
	out := new(Comment)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.DeleteComment", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionService) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...client.CallOption) (*ListCommentsResponse, error) {
	req := c.c.NewRequest(c.name, "InteractionService.ListComments", in)
	out := new(ListCommentsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InteractionService service

type InteractionServiceHandler interface {
	// 点赞
	CreateLike(context.Context, *LikeRequest, *ActionResponse) error
	DeleteLike(context.Context, *LikeRequest, *ActionResponse) error
	IsLike(context.Context, *IsLikeRequest, *IsLikeResponse) error
	ListLikes(context.Context, *ListLikesRequest, *ListLikesResponse) error
	// 收藏
	CreateFavorite(context.Context, *FavoriteRequest, *ActionResponse) error
	DeleteFavorite(context.Context, *FavoriteRequest, *ActionResponse) error
	IsFavorite(context.Context, *IsFavoriteRequest, *IsFavoriteResponse) error
	// 关注
	CreateFollow(context.Context, *FollowRequest, *ActionResponse) error
	DeleteFollow(context.Context, *FollowRequest, *ActionResponse) error
	IsFollow(context.Context, *IsFollowRequest, *IsFollowResponse) error
	ListFollowers(context.Context, *ListFollowersRequest, *ListFollowersResponse) error
	ListFollowings(context.Context, *ListFollowingsRequest, *ListFollowingsResponse) error
	// 评论
	CreateComment(context.Context, *CreateCommentRequest, *Comment) error
	DeleteComment(context.Context, *DeleteCommentRequest, *ActionResponse) error
	ListComments(context.Context, *ListCommentsRequest, *ListCommentsResponse) error
}

func RegisterInteractionServiceHandler(s server.Server, hdlr InteractionServiceHandler, opts ...server.HandlerOption) error {
	type interactionService interface {
		CreateLike(ctx context.Context, in *LikeRequest, out *ActionResponse) error
		DeleteLike(ctx context.Context, in *LikeRequest, out *ActionResponse) error
		IsLike(ctx context.Context, in *IsLikeRequest, out *IsLikeResponse) error
		ListLikes(ctx context.Context, in *ListLikesRequest, out *ListLikesResponse) error
		CreateFavorite(ctx context.Context, in *FavoriteRequest, out *ActionResponse) error
		DeleteFavorite(ctx context.Context, in *FavoriteRequest, out *ActionResponse) error
		IsFavorite(ctx context.Context, in *IsFavoriteRequest, out *IsFavoriteResponse) error
		CreateFollow(ctx context.Context, in *FollowRequest, out *ActionResponse) error
		DeleteFollow(ctx context.Context, in *FollowRequest, out *ActionResponse) error
		IsFollow(ctx context.Context, in *IsFollowRequest, out *IsFollowResponse) error
		ListFollowers(ctx context.Context, in *ListFollowersRequest, out *ListFollowersResponse) error
		ListFollowings(ctx context.Context, in *ListFollowingsRequest, out *ListFollowingsResponse) error
		CreateComment(ctx context.Context, in *CreateCommentRequest, out *Comment) error
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, out *ActionResponse) error
		ListComments(ctx context.Context, in *ListCommentsRequest, out *ListCommentsResponse) error
	}
	type InteractionService struct {
		interactionService
	}
	h := &interactionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&InteractionService{h}, opts...))
}

type interactionServiceHandler struct {
	InteractionServiceHandler
}

func (h *interactionServiceHandler) CreateLike(ctx context.Context, in *LikeRequest, out *ActionResponse) error {
	return h.InteractionServiceHandler.CreateLike(ctx, in, out)
}

func (h *interactionServiceHandler) DeleteLike(ctx context.Context, in *LikeRequest, out *ActionResponse) error {
	return h.InteractionServiceHandler.DeleteLike(ctx, in, out)
}

func (h *interactionServiceHandler) IsLike(ctx context.Context, in *IsLikeRequest, out *IsLikeResponse) error {
	return h.InteractionServiceHandler.IsLike(ctx, in, out)
}

func (h *interactionServiceHandler) ListLikes(ctx context.Context, in *ListLikesRequest, out *ListLikesResponse) error {
	return h.InteractionServiceHandler.ListLikes(ctx, in, out)
}

func (h *interactionServiceHandler) CreateFavorite(ctx context.Context, in *FavoriteRequest, out *ActionResponse) error {
	return h.InteractionServiceHandler.CreateFavorite(ctx, in, out)
}

func (h *interactionServiceHandler) DeleteFavorite(ctx context.Context, in *FavoriteRequest, out *ActionResponse) error {
	return h.InteractionServiceHandler.DeleteFavorite(ctx, in, out)
}

func (h *interactionServiceHandler) IsFavorite(ctx context.Context, in *IsFavoriteRequest, out *IsFavoriteResponse) error {
	return h.InteractionServiceHandler.IsFavorite(ctx, in, out)
}

func (h *interactionServiceHandler) CreateFollow(ctx context.Context, in *FollowRequest, out *ActionResponse) error {
	return h.InteractionServiceHandler.CreateFollow(ctx, in, out)
}

func (h *interactionServiceHandler) DeleteFollow(ctx context.Context, in *FollowRequest, out *ActionResponse) error {
	return h.InteractionServiceHandler.DeleteFollow(ctx, in, out)
}

func (h *interactionServiceHandler) IsFollow(ctx context.Context, in *IsFollowRequest, out *IsFollowResponse) error {
	return h.InteractionServiceHandler.IsFollow(ctx, in, out)
}

func (h *interactionServiceHandler) ListFollowers(ctx context.Context, in *ListFollowersRequest, out *ListFollowersResponse) error {
	return h.InteractionServiceHandler.ListFollowers(ctx, in, out)
}

func (h *interactionServiceHandler) ListFollowings(ctx context.Context, in *ListFollowingsRequest, out *ListFollowingsResponse) error {
	return h.InteractionServiceHandler.ListFollowings(ctx, in, out)
}

func (h *interactionServiceHandler) CreateComment(ctx context.Context, in *CreateCommentRequest, out *Comment) error {
	return h.InteractionServiceHandler.CreateComment(ctx, in, out)
}

func (h *interactionServiceHandler) DeleteComment(ctx context.Context, in *DeleteCommentRequest, out *ActionResponse) error {
	return h.InteractionServiceHandler.DeleteComment(ctx, in, out)
}

func (h *interactionServiceHandler) ListComments(ctx context.Context, in *ListCommentsRequest, out *ListCommentsResponse) error {
	return h.InteractionServiceHandler.ListComments(ctx, in, out)
}
