// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: interaction.proto

package interaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`           // 昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`               // 头像
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`         // 个性签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserView) Reset() {
	*x = UserView{}
	mi := &file_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserView) ProtoMessage() {}

func (x *UserView) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserView.ProtoReflect.Descriptor instead.
func (*UserView) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *UserView) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserView) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserView) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserView) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *LikeRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type IsLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikeRequest) Reset() {
	*x = IsLikeRequest{}
	mi := &file_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikeRequest) ProtoMessage() {}

func (x *IsLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikeRequest.ProtoReflect.Descriptor instead.
func (*IsLikeRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *IsLikeRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type IsLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLike        bool                   `protobuf:"varint,1,opt,name=is_like,json=isLike,proto3" json:"is_like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikeResponse) Reset() {
	*x = IsLikeResponse{}
	mi := &file_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikeResponse) ProtoMessage() {}

func (x *IsLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikeResponse.ProtoReflect.Descriptor instead.
func (*IsLikeResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *IsLikeResponse) GetIsLike() bool {
	if x != nil {
		return x.IsLike
	}
	return false
}

type ListLikesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLikesRequest) Reset() {
	*x = ListLikesRequest{}
	mi := &file_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLikesRequest) ProtoMessage() {}

func (x *ListLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLikesRequest.ProtoReflect.Descriptor instead.
func (*ListLikesRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *ListLikesRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ListLikesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLikesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListLikesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserView            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLikesResponse) Reset() {
	*x = ListLikesResponse{}
	mi := &file_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLikesResponse) ProtoMessage() {}

func (x *ListLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLikesResponse.ProtoReflect.Descriptor instead.
func (*ListLikesResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *ListLikesResponse) GetUsers() []*UserView {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListLikesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type FavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteRequest) Reset() {
	*x = FavoriteRequest{}
	mi := &file_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteRequest) ProtoMessage() {}

func (x *FavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteRequest.ProtoReflect.Descriptor instead.
func (*FavoriteRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *FavoriteRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type IsFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoriteRequest) Reset() {
	*x = IsFavoriteRequest{}
	mi := &file_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoriteRequest) ProtoMessage() {}

func (x *IsFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoriteRequest.ProtoReflect.Descriptor instead.
func (*IsFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *IsFavoriteRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type IsFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFavorite    bool                   `protobuf:"varint,1,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoriteResponse) Reset() {
	*x = IsFavoriteResponse{}
	mi := &file_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoriteResponse) ProtoMessage() {}

func (x *IsFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoriteResponse.ProtoReflect.Descriptor instead.
func (*IsFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *IsFavoriteResponse) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  string                 `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *FollowRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type IsFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  string                 `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowRequest) Reset() {
	*x = IsFollowRequest{}
	mi := &file_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowRequest) ProtoMessage() {}

func (x *IsFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowRequest.ProtoReflect.Descriptor instead.
func (*IsFollowRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *IsFollowRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type IsFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollow      bool                   `protobuf:"varint,1,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowResponse) Reset() {
	*x = IsFollowResponse{}
	mi := &file_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowResponse) ProtoMessage() {}

func (x *IsFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowResponse.ProtoReflect.Descriptor instead.
func (*IsFollowResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *IsFollowResponse) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

type ListFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersRequest) Reset() {
	*x = ListFollowersRequest{}
	mi := &file_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersRequest) ProtoMessage() {}

func (x *ListFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersRequest.ProtoReflect.Descriptor instead.
func (*ListFollowersRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *ListFollowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFollowersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFollowersRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFollowingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingsRequest) Reset() {
	*x = ListFollowingsRequest{}
	mi := &file_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingsRequest) ProtoMessage() {}

func (x *ListFollowingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingsRequest.ProtoReflect.Descriptor instead.
func (*ListFollowingsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *ListFollowingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFollowingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFollowingsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserView            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersResponse) Reset() {
	*x = ListFollowersResponse{}
	mi := &file_interaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersResponse) ProtoMessage() {}

func (x *ListFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersResponse.ProtoReflect.Descriptor instead.
func (*ListFollowersResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{15}
}

func (x *ListFollowersResponse) GetUsers() []*UserView {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListFollowersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListFollowingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserView            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingsResponse) Reset() {
	*x = ListFollowingsResponse{}
	mi := &file_interaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingsResponse) ProtoMessage() {}

func (x *ListFollowingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingsResponse.ProtoReflect.Descriptor instead.
func (*ListFollowingsResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{16}
}

func (x *ListFollowingsResponse) GetUsers() []*UserView {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListFollowingsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                    // 一级评论传 "0"
	ReplyToUserId string                 `protobuf:"bytes,4,opt,name=reply_to_user_id,json=replyToUserId,proto3" json:"reply_to_user_id,omitempty"` // 可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_interaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCommentRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateCommentRequest) GetReplyToUserId() string {
	if x != nil {
		return x.ReplyToUserId
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_interaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_interaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Comment struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId  string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 冗余字段，用于展示
	Nickname      string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Content       string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      string `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                    // "0" 表示一级评论
	ReplyToUserId string `protobuf:"bytes,8,opt,name=reply_to_user_id,json=replyToUserId,proto3" json:"reply_to_user_id,omitempty"` // 可选
	LikeCount     int64  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`                // 只读（无点赞接口）
	ReplyCount    int64  `protobuf:"varint,10,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	CreateTime    int64  `protobuf:"varint,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_interaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{20}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Comment) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Comment) GetReplyToUserId() string {
	if x != nil {
		return x.ReplyToUserId
	}
	return ""
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Comment) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ListCommentsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VideoId  string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Page     int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 一级评论 or 子评论
	ParentId      string `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // "0" 拉一级评论
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_interaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{21}
}

func (x *ListCommentsRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ListCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommentsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_interaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{22}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCommentsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_interaction_proto protoreflect.FileDescriptor

const file_interaction_proto_rawDesc = "" +
	"\n" +
	"\x11interaction.proto\x12\x16stream_hub.interaction\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"u\n" +
	"\bUserView\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"(\n" +
	"\vLikeRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"*\n" +
	"\rIsLikeRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\")\n" +
	"\x0eIsLikeResponse\x12\x17\n" +
	"\ais_like\x18\x01 \x01(\bR\x06isLike\"U\n" +
	"\x10ListLikesRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"a\n" +
	"\x11ListLikesResponse\x126\n" +
	"\x05users\x18\x01 \x03(\v2 .stream_hub.interaction.UserViewR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\",\n" +
	"\x0fFavoriteRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\".\n" +
	"\x11IsFavoriteRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"5\n" +
	"\x12IsFavoriteResponse\x12\x1f\n" +
	"\vis_favorite\x18\x01 \x01(\bR\n" +
	"isFavorite\"5\n" +
	"\rFollowRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\tR\ftargetUserId\"7\n" +
	"\x0fIsFollowRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\tR\ftargetUserId\"/\n" +
	"\x10IsFollowResponse\x12\x1b\n" +
	"\tis_follow\x18\x01 \x01(\bR\bisFollow\"W\n" +
	"\x14ListFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"X\n" +
	"\x15ListFollowingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"e\n" +
	"\x15ListFollowersResponse\x126\n" +
	"\x05users\x18\x01 \x03(\v2 .stream_hub.interaction.UserViewR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"f\n" +
	"\x16ListFollowingsResponse\x126\n" +
	"\x05users\x18\x01 \x03(\v2 .stream_hub.interaction.UserViewR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x91\x01\n" +
	"\x14CreateCommentRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12'\n" +
	"\x10reply_to_user_id\x18\x04 \x01(\tR\rreplyToUserId\"5\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc2\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12'\n" +
	"\x10reply_to_user_id\x18\b \x01(\tR\rreplyToUserId\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x03R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\n" +
	" \x01(\x03R\n" +
	"replyCount\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\x03R\n" +
	"createTime\"~\n" +
	"\x13ListCommentsRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"\x84\x01\n" +
	"\x14ListCommentsResponse\x12;\n" +
	"\bcomments\x18\x01 \x03(\v2\x1f.stream_hub.interaction.CommentR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\xde\v\n" +
	"\x12InteractionService\x12Y\n" +
	"\n" +
	"CreateLike\x12#.stream_hub.interaction.LikeRequest\x1a&.stream_hub.interaction.ActionResponse\x12Y\n" +
	"\n" +
	"DeleteLike\x12#.stream_hub.interaction.LikeRequest\x1a&.stream_hub.interaction.ActionResponse\x12W\n" +
	"\x06IsLike\x12%.stream_hub.interaction.IsLikeRequest\x1a&.stream_hub.interaction.IsLikeResponse\x12`\n" +
	"\tListLikes\x12(.stream_hub.interaction.ListLikesRequest\x1a).stream_hub.interaction.ListLikesResponse\x12a\n" +
	"\x0eCreateFavorite\x12'.stream_hub.interaction.FavoriteRequest\x1a&.stream_hub.interaction.ActionResponse\x12a\n" +
	"\x0eDeleteFavorite\x12'.stream_hub.interaction.FavoriteRequest\x1a&.stream_hub.interaction.ActionResponse\x12c\n" +
	"\n" +
	"IsFavorite\x12).stream_hub.interaction.IsFavoriteRequest\x1a*.stream_hub.interaction.IsFavoriteResponse\x12]\n" +
	"\fCreateFollow\x12%.stream_hub.interaction.FollowRequest\x1a&.stream_hub.interaction.ActionResponse\x12]\n" +
	"\fDeleteFollow\x12%.stream_hub.interaction.FollowRequest\x1a&.stream_hub.interaction.ActionResponse\x12]\n" +
	"\bIsFollow\x12'.stream_hub.interaction.IsFollowRequest\x1a(.stream_hub.interaction.IsFollowResponse\x12l\n" +
	"\rListFollowers\x12,.stream_hub.interaction.ListFollowersRequest\x1a-.stream_hub.interaction.ListFollowersResponse\x12o\n" +
	"\x0eListFollowings\x12-.stream_hub.interaction.ListFollowingsRequest\x1a..stream_hub.interaction.ListFollowingsResponse\x12^\n" +
	"\rCreateComment\x12,.stream_hub.interaction.CreateCommentRequest\x1a\x1f.stream_hub.interaction.Comment\x12e\n" +
	"\rDeleteComment\x12,.stream_hub.interaction.DeleteCommentRequest\x1a&.stream_hub.interaction.ActionResponse\x12i\n" +
	"\fListComments\x12+.stream_hub.interaction.ListCommentsRequest\x1a,.stream_hub.interaction.ListCommentsResponseB\x0fZ\r./interactionb\x06proto3"

var (
	file_interaction_proto_rawDescOnce sync.Once
	file_interaction_proto_rawDescData []byte
)

func file_interaction_proto_rawDescGZIP() []byte {
	file_interaction_proto_rawDescOnce.Do(func() {
		file_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)))
	})
	return file_interaction_proto_rawDescData
}

var file_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_interaction_proto_goTypes = []any{
	(*ActionResponse)(nil),         // 0: stream_hub.interaction.ActionResponse
	(*UserView)(nil),               // 1: stream_hub.interaction.UserView
	(*LikeRequest)(nil),            // 2: stream_hub.interaction.LikeRequest
	(*IsLikeRequest)(nil),          // 3: stream_hub.interaction.IsLikeRequest
	(*IsLikeResponse)(nil),         // 4: stream_hub.interaction.IsLikeResponse
	(*ListLikesRequest)(nil),       // 5: stream_hub.interaction.ListLikesRequest
	(*ListLikesResponse)(nil),      // 6: stream_hub.interaction.ListLikesResponse
	(*FavoriteRequest)(nil),        // 7: stream_hub.interaction.FavoriteRequest
	(*IsFavoriteRequest)(nil),      // 8: stream_hub.interaction.IsFavoriteRequest
	(*IsFavoriteResponse)(nil),     // 9: stream_hub.interaction.IsFavoriteResponse
	(*FollowRequest)(nil),          // 10: stream_hub.interaction.FollowRequest
	(*IsFollowRequest)(nil),        // 11: stream_hub.interaction.IsFollowRequest
	(*IsFollowResponse)(nil),       // 12: stream_hub.interaction.IsFollowResponse
	(*ListFollowersRequest)(nil),   // 13: stream_hub.interaction.ListFollowersRequest
	(*ListFollowingsRequest)(nil),  // 14: stream_hub.interaction.ListFollowingsRequest
	(*ListFollowersResponse)(nil),  // 15: stream_hub.interaction.ListFollowersResponse
	(*ListFollowingsResponse)(nil), // 16: stream_hub.interaction.ListFollowingsResponse
	(*CreateCommentRequest)(nil),   // 17: stream_hub.interaction.CreateCommentRequest
	(*DeleteCommentRequest)(nil),   // 18: stream_hub.interaction.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),  // 19: stream_hub.interaction.DeleteCommentResponse
	(*Comment)(nil),                // 20: stream_hub.interaction.Comment
	(*ListCommentsRequest)(nil),    // 21: stream_hub.interaction.ListCommentsRequest
	(*ListCommentsResponse)(nil),   // 22: stream_hub.interaction.ListCommentsResponse
}
var file_interaction_proto_depIdxs = []int32{
	1,  // 0: stream_hub.interaction.ListLikesResponse.users:type_name -> stream_hub.interaction.UserView
	1,  // 1: stream_hub.interaction.ListFollowersResponse.users:type_name -> stream_hub.interaction.UserView
	1,  // 2: stream_hub.interaction.ListFollowingsResponse.users:type_name -> stream_hub.interaction.UserView
	20, // 3: stream_hub.interaction.ListCommentsResponse.comments:type_name -> stream_hub.interaction.Comment
	2,  // 4: stream_hub.interaction.InteractionService.CreateLike:input_type -> stream_hub.interaction.LikeRequest
	2,  // 5: stream_hub.interaction.InteractionService.DeleteLike:input_type -> stream_hub.interaction.LikeRequest
	3,  // 6: stream_hub.interaction.InteractionService.IsLike:input_type -> stream_hub.interaction.IsLikeRequest
	5,  // 7: stream_hub.interaction.InteractionService.ListLikes:input_type -> stream_hub.interaction.ListLikesRequest
	7,  // 8: stream_hub.interaction.InteractionService.CreateFavorite:input_type -> stream_hub.interaction.FavoriteRequest
	7,  // 9: stream_hub.interaction.InteractionService.DeleteFavorite:input_type -> stream_hub.interaction.FavoriteRequest
	8,  // 10: stream_hub.interaction.InteractionService.IsFavorite:input_type -> stream_hub.interaction.IsFavoriteRequest
	10, // 11: stream_hub.interaction.InteractionService.CreateFollow:input_type -> stream_hub.interaction.FollowRequest
	10, // 12: stream_hub.interaction.InteractionService.DeleteFollow:input_type -> stream_hub.interaction.FollowRequest
	11, // 13: stream_hub.interaction.InteractionService.IsFollow:input_type -> stream_hub.interaction.IsFollowRequest
	13, // 14: stream_hub.interaction.InteractionService.ListFollowers:input_type -> stream_hub.interaction.ListFollowersRequest
	14, // 15: stream_hub.interaction.InteractionService.ListFollowings:input_type -> stream_hub.interaction.ListFollowingsRequest
	17, // 16: stream_hub.interaction.InteractionService.CreateComment:input_type -> stream_hub.interaction.CreateCommentRequest
	18, // 17: stream_hub.interaction.InteractionService.DeleteComment:input_type -> stream_hub.interaction.DeleteCommentRequest
	21, // 18: stream_hub.interaction.InteractionService.ListComments:input_type -> stream_hub.interaction.ListCommentsRequest
	0,  // 19: stream_hub.interaction.InteractionService.CreateLike:output_type -> stream_hub.interaction.ActionResponse
	0,  // 20: stream_hub.interaction.InteractionService.DeleteLike:output_type -> stream_hub.interaction.ActionResponse
	4,  // 21: stream_hub.interaction.InteractionService.IsLike:output_type -> stream_hub.interaction.IsLikeResponse
	6,  // 22: stream_hub.interaction.InteractionService.ListLikes:output_type -> stream_hub.interaction.ListLikesResponse
	0,  // 23: stream_hub.interaction.InteractionService.CreateFavorite:output_type -> stream_hub.interaction.ActionResponse
	0,  // 24: stream_hub.interaction.InteractionService.DeleteFavorite:output_type -> stream_hub.interaction.ActionResponse
	9,  // 25: stream_hub.interaction.InteractionService.IsFavorite:output_type -> stream_hub.interaction.IsFavoriteResponse
	0,  // 26: stream_hub.interaction.InteractionService.CreateFollow:output_type -> stream_hub.interaction.ActionResponse
	0,  // 27: stream_hub.interaction.InteractionService.DeleteFollow:output_type -> stream_hub.interaction.ActionResponse
	12, // 28: stream_hub.interaction.InteractionService.IsFollow:output_type -> stream_hub.interaction.IsFollowResponse
	15, // 29: stream_hub.interaction.InteractionService.ListFollowers:output_type -> stream_hub.interaction.ListFollowersResponse
	16, // 30: stream_hub.interaction.InteractionService.ListFollowings:output_type -> stream_hub.interaction.ListFollowingsResponse
	20, // 31: stream_hub.interaction.InteractionService.CreateComment:output_type -> stream_hub.interaction.Comment
	0,  // 32: stream_hub.interaction.InteractionService.DeleteComment:output_type -> stream_hub.interaction.ActionResponse
	22, // 33: stream_hub.interaction.InteractionService.ListComments:output_type -> stream_hub.interaction.ListCommentsResponse
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_interaction_proto_init() }
func file_interaction_proto_init() {
	if File_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_proto_depIdxs,
		MessageInfos:      file_interaction_proto_msgTypes,
	}.Build()
	File_interaction_proto = out.File
	file_interaction_proto_goTypes = nil
	file_interaction_proto_depIdxs = nil
}
